### ISSUE TITLE
cpio: Input/output error

### ISSUE THREAD

**Issue by KayGau** [ssc-oscar/libgit2#11]
When I am preparing for batch_fetch.c input, I met 2 problems:
1. I have no permission to write to the da0:/da0_data/cpio and da0:/da0_data/play
2. I copy a .cpio.gz to my home folder, and run zcat .cpio.gz | cpio -id, occur an error:
kgao@da0:~/list201910.Q1.35>zcat ../list201910.Q1.35.cpio.gz | cpio -id
cpio: cannot make directory `doramart_egg-dora-contenttemp': Input/output error
cpio: doramart_egg-dora-contenttemp/packed-refs: Cannot open: Remote I/O error
cpio: dotnib_sabury/packed-refs: Cannot open: Input/output error
cpio: doulos76_iOS_UI_Test/packed-refs: Cannot open: Input/output error
cpio: dpnbp_dpnbp.github.io: Cannot stat: Remote I/O error
cpio: drengskapr_rebrain-devops-task-checkout: Cannot stat: Remote I/O error
cpio: droidfanat_artrunner/packed-refs: Cannot change mode to rw-r--r--: Remote I/O error
cpio: droidfanat_artrunner/packed-refs: Cannot close: Input/output error
cpio: dswatson_bioplotr/packed-refs: Cannot change mode to rw-r--r--: Remote I/O error
cpio: dswatson_bioplotr/packed-refs: Cannot close: Input/output error
cpio: ducga1998_page-builder-duc/packed-refs: Cannot change mode to rw-r--r--: Input/output error
cpio: dump14040161_frsystem04/packed-refs: Cannot change mode to rw-r--r--: Input/output error

**Comment by audrism** [comment]
Please run on da2 if files are in your home folder or create subfolder in /data/play as noted in the tutorial.

**Comment by KayGau** [comment]
Solved, thank you!
